### ISSUE TITLE
issue in ranknet training with python 3.6

### ISSUE THREAD

**Issue by DmitryKey** [airalcorn2/Solr-LTR#9]
Hi,
I finally made to the RankNet training. Thanks a lot for sharing the tutorial!

The issue I experience at this point is related wrong inputs. It could be because I do not have full set of 50 documents per query. But could there be some other reason too?

`Using Theano backend.
Traceback (most recent call last):
  File "ranknet.py", line 111, in <module>
    callbacks=[checkpointer], verbose=3)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 950, in fit
    batch_size=batch_size)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training.py", line 749, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/training_utils.py", line 127, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 2 dimensions, but got array with shape (0, 0, 6)`

**Comment by airalcorn2** [comment]
Your data has a very strange shape. It should resemble the data [here](https://github.com/airalcorn2/RankNet/blob/master/ranknet.py#L44). That is, it should have a shape of `(N, number_of_features)`.
